-- Q5: How does shot generation relate to match result?
-- shots, result relationship
-- This query calculates the total number of shots generated by each team in a match and relates it to the match result (win, loss, or draw). 
-- season, team, total_shots, avg_shots_per_match, wins, draws, losses, points
-- home and away team perspective
CREATE OR REPLACE VIEW gold.laliga_shot_generation AS
SELECT
    season,
    team,
    SUM(shots) AS total_shots,
    ROUND(AVG(shots), 0) AS avg_shots_per_match,
    COUNT(
        CASE
            WHEN result = 'W' THEN 1
        END
    ) AS wins,
    COUNT(
        CASE
            WHEN result = 'D' THEN 1
        END
    ) AS draws,
    COUNT(
        CASE
            WHEN result = 'L' THEN 1
        END
    ) AS losses
FROM
    (
        SELECT
            season,
            home_team AS team,
            home_team_shots AS shots,
            CASE
                WHEN full_time_result = 'H' THEN 'W'
                WHEN full_time_result = 'D' THEN 'D'
                WHEN full_time_result = 'A' THEN 'L'
            END AS result
        FROM
            silver.laliga_matches
        UNION ALL
        SELECT
            season,
            away_team AS team,
            away_team_shots AS shots,
            CASE
                WHEN full_time_result = 'A' THEN 'W'
                WHEN full_time_result = 'D' THEN 'D'
                WHEN full_time_result = 'H' THEN 'L'
            END AS result
        FROM
            silver.laliga_matches
    ) AS combined
GROUP BY
    season,
    team
    -- test the view
SELECT
    *
FROM
    gold.laliga_shot_generation;

-- perform analysis for 22-23 season
SELECT
    *
FROM
    gold.laliga_shot_generation
WHERE
    season = '2022-2023'
ORDER BY
    season,
    total_shots DESC;

-- 23-24 season analysis
SELECT
    *
FROM
    gold.laliga_shot_generation
WHERE
    season = '2023-2024'
ORDER BY
    season,
    total_shots DESC;

-- 24-25 season analysis
SELECT
    *
FROM
    gold.laliga_shot_generation
WHERE
    season = '2024-2025'
ORDER BY
    season,
    total_shots DESC;

-- 25-26 season analysis
SELECT
    *
FROM
    gold.laliga_shot_generation
WHERE
    season = '2025-2026'
ORDER BY
    season,
    total_shots DESC;